name: pboproject

on:
  push:


jobs:
  pboproject:
    runs-on: windows-2019
    steps:
    
   
      
    - name: Download game data
      run: |
        Invoke-WebRequest "$env:ARMA3_DATA_URL" -OutFile arma3.zip
        $files = @("arma3.zip")
        ForEach ($file in $files) {
          Extract-7Zip -Path $file -DestinationPath .
          Remove-Item $file
        }
      env:
        ARMA3_DATA_URL: ${{ secrets.ARMA3_DATA_URL }}

    - name: Checkout H-60
      uses: actions/checkout@v2
      with:
        path: z\vtx
        persist-credentials: false

    - name: Setup build environment
      run: |
        subst P: .
        pboproject -P
        
    - name: Build
      run: py P:\z\vtx\tools\make.py ci
      env:
        PYTHONUNBUFFERED: 1
        
    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: logs
        path: temp/*.log

    - name: Upload to steam
      uses: arma-actions/workshop-upload@v1
      with:
        appId: '107410'    # default
        itemId: '2607181671' # Id of item to update
        contentPath: 'releases/${{ env.VERSION }}/@H-60 Release Candidate'
        changelog: 'Content of change notes'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
